// Fixed metadata per outlet. The crawler merges parser output into these shells.
// Keep this in sync with the shape consumed by public/data.js / shared.jsx.

export const OUTLETS = [
  {
    id: "chosun",
    name: "조선일보",
    nameEn: "The Chosun Ilbo",
    lang: "ko",
    country: "KR",
    url: "https://www.chosun.com",
    editorialUrl: "https://www.chosun.com/opinion/editorial/",
    lean: "보수",
    leanEn: "Conservative",
    leanColor: "#B8342B",
    est: 1920,
    circulation: "1.2M",
    gated: false,
  },
  {
    id: "wsj",
    name: "The Wall Street Journal",
    nameEn: "The Wall Street Journal",
    lang: "en",
    country: "US",
    url: "https://www.wsj.com",
    editorialUrl: "https://www.wsj.com/opinion",
    lean: "Conservative",
    leanEn: "Conservative",
    leanColor: "#0274B6",
    est: 1889,
    circulation: "2.8M",
    gated: true, // paywall — meta + link only
  },
  {
    id: "hankook",
    name: "한국일보",
    nameEn: "The Hankook Ilbo",
    lang: "ko",
    country: "KR",
    url: "https://www.hankookilbo.com",
    editorialUrl: "https://www.hankookilbo.com/Collection/7340",
    lean: "중도",
    leanEn: "Centrist",
    leanColor: "#4A6B52",
    est: 1954,
    circulation: "280K",
    gated: false,
  },
  {
    id: "koreatimes",
    name: "The Korea Times",
    nameEn: "The Korea Times",
    lang: "en",
    country: "KR",
    url: "https://www.koreatimes.co.kr",
    editorialUrl: "https://www.koreatimes.co.kr/www/opinion/editorial.html",
    lean: "Center",
    leanEn: "Center",
    leanColor: "#2E5C8A",
    est: 1950,
    circulation: "160K",
    gated: false,
  },
  {
    id: "joongang",
    name: "중앙일보",
    nameEn: "The JoongAng",
    lang: "ko",
    country: "KR",
    url: "https://www.joongang.co.kr",
    editorialUrl: "https://www.joongang.co.kr/opinion",
    lean: "중도보수",
    leanEn: "Center-Right",
    leanColor: "#1F4B8E",
    est: 1965,
    circulation: "720K",
    gated: false,
  },
  {
    id: "heraldcorp",
    name: "The Korea Herald",
    nameEn: "The Korea Herald",
    lang: "en",
    country: "KR",
    url: "https://www.koreaherald.com",
    editorialUrl: "https://www.koreaherald.com/list.php?ct=020108000000",
    lean: "Center",
    leanEn: "Center",
    leanColor: "#00653A",
    est: 1953,
    circulation: "140K",
    gated: false,
  },
  {
    id: "nyt",
    name: "The New York Times",
    nameEn: "The New York Times",
    lang: "en",
    country: "US",
    url: "https://www.nytimes.com",
    editorialUrl: "https://www.nytimes.com/section/opinion/editorials",
    lean: "Liberal",
    leanEn: "Liberal",
    leanColor: "#121212",
    est: 1851,
    circulation: "9.7M",
    gated: true,
  },
  {
    id: "ft",
    name: "Financial Times",
    nameEn: "Financial Times",
    lang: "en",
    country: "UK",
    url: "https://www.ft.com",
    editorialUrl: "https://www.ft.com/opinion",
    lean: "Center-Liberal",
    leanEn: "Center-Liberal",
    leanColor: "#FFF1E5",
    leanTextColor: "#990F3D",
    est: 1888,
    circulation: "1.1M",
    gated: true,
  },
];
