// Fixed metadata per outlet. The crawler merges parser output into these shells.
// Keep this in sync with the shape consumed by public/data.js / shared.jsx.

export const OUTLETS = [
  // --- MAIN 4 (full body + LLM summary) ---
  {
    id: "koreatimes",
    name: "The Korea Times",
    nameEn: "The Korea Times",
    lang: "en",
    country: "KR",
    url: "https://www.koreatimes.co.kr",
    editorialUrl: "https://www.koreatimes.co.kr/opinion/editorial",
    lean: "Center",
    leanEn: "Center",
    leanColor: "#2E5C8A",
    est: 1950,
    circulation: "160K",
    gated: false,
  },
  {
    id: "hankook",
    name: "한국일보",
    nameEn: "The Hankook Ilbo",
    lang: "ko",
    country: "KR",
    url: "https://www.hankookilbo.com",
    editorialUrl: "https://www.hankookilbo.com/news/opinion/editorial",
    lean: "중도",
    leanEn: "Centrist",
    leanColor: "#4A6B52",
    est: 1954,
    circulation: "280K",
    gated: false,
  },
  {
    id: "chosun",
    name: "조선일보",
    nameEn: "The Chosun Ilbo",
    lang: "ko",
    country: "KR",
    url: "https://www.chosun.com",
    editorialUrl: "https://www.chosun.com/opinion/editorial/",
    lean: "보수",
    leanEn: "Conservative",
    leanColor: "#B8342B",
    est: 1920,
    circulation: "1.2M",
    gated: false,
  },
  {
    id: "joongang",
    name: "중앙일보",
    nameEn: "The JoongAng",
    lang: "ko",
    country: "KR",
    url: "https://www.joongang.co.kr",
    editorialUrl: "https://www.joongang.co.kr/opinion",
    lean: "중도보수",
    leanEn: "Center-Right",
    leanColor: "#1F4B8E",
    est: 1965,
    circulation: "720K",
    gated: false,
  },
  // --- SUB 4 (simpler cards) ---
  {
    id: "heraldcorp",
    name: "The Korea Herald",
    nameEn: "The Korea Herald",
    lang: "en",
    country: "KR",
    url: "https://www.koreaherald.com",
    editorialUrl: "https://www.koreaherald.com/Opinion/Editorial",
    lean: "Center",
    leanEn: "Center",
    leanColor: "#00653A",
    est: 1953,
    circulation: "140K",
    gated: false,
  },
  {
    id: "hani",
    name: "한겨레",
    nameEn: "The Hankyoreh",
    lang: "ko",
    country: "KR",
    url: "https://www.hani.co.kr",
    editorialUrl: "https://www.hani.co.kr/arti/opinion/editorial",
    lean: "진보",
    leanEn: "Progressive",
    leanColor: "#1f7a52",
    est: 1988,
    circulation: "240K",
    gated: false,
  },
  {
    id: "mk",
    name: "매일경제",
    nameEn: "Maeil Business News",
    lang: "ko",
    country: "KR",
    url: "https://www.mk.co.kr",
    editorialUrl: "https://www.mk.co.kr/opinion",
    lean: "경제보수",
    leanEn: "Pro-business",
    leanColor: "#0f3e87",
    est: 1966,
    circulation: "600K",
    gated: false,
  },
  {
    id: "hankyung",
    name: "한국경제",
    nameEn: "The Korea Economic Daily",
    lang: "ko",
    country: "KR",
    url: "https://www.hankyung.com",
    editorialUrl: "https://www.hankyung.com/opinion",
    lean: "경제보수",
    leanEn: "Pro-business",
    leanColor: "#1a5fa8",
    est: 1964,
    circulation: "400K",
    gated: false,
  },
];
